### ISSUE TITLE
Please define a license

### ISSUE THREAD

**Issue by lilianmoraru** [pcwalton/gaol#7]
Can you please create a `LICENSE` file with the license of the project, so interested people can decide on whether they can use the library in their projects?
My guess would be that it is `MPL 2.0` but I saw that Servo uses `rust-clipboard` which is `GPLv2`...
Btw, this is to me strange because shouldn't GPL plague the license up the chain and make Servo also GPLv2? Or the author gave consent?

Edit: The code seems to say ASL 2.0

**Comment by frewsxcv** [comment]
https://github.com/pcwalton/gaol/commit/5362252bbed12ba33922a708b05e357c4e649324
